services:
  - type: web
    plan: free
    name: ProMegaDownloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/SHIVANSH475/PORN-BOT
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_URL
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
